bind = "127.0.0.1:5000"
workers = 3
worker_class = "sync"
worker_connections = 1000
timeout = 30
keepalive = 2
max_requests = 1000
max_requests_jitter = 100
preload_app = True
reload = False
daemon = False
user = "root"
group = "root"
logfile = "/var/log/gunicorn/sistema_consul.log"
loglevel = "info"
access_logfile = "/var/log/gunicorn/sistema_consul_access.log"
access_logformat = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
